const {JSDOM}=require('jsdom');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const fixture=require('./glb-fixture.cjs');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');
const glb='11111111-1111-4111-8111-111111111111.glb';
async function run(){
 const dom=new JSDOM(read('index.html'),{url:'https://shop.example.test',runScripts:'outside-only',pretendToBeVisual:true});
 const w=dom.window,$=id=>w.document.getElementById(id);
 w.alert=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};
 w.HTMLCanvasElement.prototype.getContext=()=>({getExtension:()=>null});
 w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
 w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};
 class Viewer extends w.HTMLElement{getCameraOrbit(){return{theta:1,phi:1,radius:2};}}
 w.customElements.define('model-viewer',Viewer);
 const base={description_de:'Deutsch',description_fr:'Français',price_50:15,price_60:20,price_70:25,stock:5,image_url:null,color_mode:'mehrfarbig',active:true};
 const rows=[{...base,id:1,name:'Cavallo',glb_path:glb},{...base,id:5,name:'Pika Urban',glb_path:glb},{...base,id:6,name:'Frugo',glb_path:null}];
 w.fetch=async()=>({ok:true,json:async()=>rows});w.eval(read('supabase-config.js'));
 const inline=[...w.document.querySelectorAll('script:not([src])')].map(s=>s.textContent).join('\n');
 w.eval(inline+'\n'+read('product-3d.js')+'\n'+read('products.js'));
 await new Promise(r=>setTimeout(r,30));
 assert.equal(w.document.querySelectorAll('.product-3d-open').length,2);
 assert.equal(w.document.querySelector('[data-catalog-id="6"] .product-3d-open'),null);
 assert.equal(w.document.querySelector('model-viewer'),null);
 assert.equal(w.Favo3D.url('../product-models/private.3mf'),null);
 assert.equal(w.Favo3D.url('https://evil.example/model.glb'),null);
 await w.Favo3D.validateFile(new File([fixture()],'preview.glb'));
 await assert.rejects(w.Favo3D.validateFile(new File([fixture()],'source.3mf')));
 await assert.rejects(w.Favo3D.validateFile(new File(['PK private 3mf'],'renamed.glb')));
 await assert.rejects(w.Favo3D.validateFile(new File([fixture({buffers:[{uri:'private.3mf'}]})],'external.glb')));
 await assert.rejects(w.Favo3D.validateFile(new File([fixture().subarray(0,40)],'truncated.glb')));
 $('openHorseConfig').click();assert.ok($('horseModal').classList.contains('open'));
 $('horseModal').classList.remove('open');
 const pika=w.document.querySelector('[data-catalog-id="5"] button:not(.heart):not(.product-3d-open)');
 pika.click();assert.ok($('pikaModal').classList.contains('open'));$('pikaModal').classList.remove('open');
 const before=[$('horseSize').value,$('pikaSize').value];
 const button=w.document.querySelector('.product-3d-open');button.click();await Promise.resolve();await Promise.resolve();
 const viewer=w.document.querySelector('model-viewer');assert.ok(viewer);assert.match(viewer.src,/public\/product-glb\//);
 assert.ok(viewer.hasAttribute('camera-controls'));assert.equal(viewer.getAttribute('touch-action'),'none');
 viewer.dispatchEvent(new w.Event('load'));w.document.querySelector('[data-zoom="in"]').click();assert.match(viewer.cameraOrbit,/1.6m/);
 w.document.documentElement.lang='fr';w.Favo3D.refreshLanguage();assert.equal(button.textContent,'Voir en 3D');
 assert.match(w.document.querySelector('.product-3d-status').textContent,/prêt/);
 viewer.dispatchEvent(new w.Event('error'));assert.match(w.document.querySelector('.product-3d-status').textContent,/indisponible/);
 w.document.querySelector('.product-3d-close').click();assert.equal(w.document.querySelector('model-viewer'),null);
 assert.deepEqual([$('horseSize').value,$('pikaSize').value],before);
 await w.eval('loadCatalog()');assert.equal(w.document.querySelectorAll('.product-3d-open').length,2);
 $('horseAdd').click();$('pikaAdd').click();assert.match($('cartItems').textContent,/Cavallo/);assert.match($('cartItems').textContent,/Pika Urban/);
 dom.window.close();console.log('PASS 3D: GLB validation, private path rejection, optional buttons, lazy viewer, zoom, DE/FR, error/close, repeated refresh, Cavallo/Pika configurators and cart.');
}
run().catch(e=>{console.error(e);process.exit(1);});
