const {JSDOM}=require('jsdom'),fs=require('node:fs'),assert=require('node:assert/strict');
const {webcrypto}=require('node:crypto');
const read=p=>fs.readFileSync(p,'utf8');
const seed=require('./product-options-seed.json');
const description='Eine sorgfältig gedruckte Figur mit vielen Details.\n\n'+('Die vollständige Produktbeschreibung bleibt erhalten. '.repeat(12))+'<img onerror="alert(1)">';
const rows=seed.map(p=>({...p,name:({1:'Cavallo',2:'Hoodie Drache',3:'Scheiben',4:'Zen Schildkröte',5:'Pika Urban'})[p.id]||'Figur '+p.id,description_de:description,description_fr:'Description complète en français. '+description,price_50:15,price_60:p.id===3?null:20,price_70:p.id===3?null:25,stock:null,active:true,image_url:null,seasons:[],photo_mode:'none',allow_wish_text:false}));
rows.push({id:80,name:'Einzelbild',description_de:'Kurze Beschreibung.',description_fr:null,price_50:12,price_60:null,price_70:null,stock:4,active:true,image_url:'https://images.example.test/product.jpg',color_regions:[],photo_mode:'none',allow_wish_text:false});
(async()=>{
 const initial=JSON.stringify(rows),dom=new JSDOM(read('index.html'),{url:'https://favo3dworld.ch/',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window,$=id=>w.document.getElementById(id);
 Object.defineProperty(w,'crypto',{value:webcrypto});w.HTMLElement.prototype.scrollIntoView=()=>{};w.alert=()=>{};w.AbortSignal=AbortSignal;
 const requests=[];w.fetch=async(url,options)=>{requests.push({url:String(url),method:options?.method||'GET'});assert.ok(String(url).includes('/rest/v1/Products'));return{ok:true,json:async()=>rows};};
 const inline=[...w.document.querySelectorAll('script:not([src])')].map(s=>s.textContent).join('\n');
 w.eval(read('supabase-config.js')+'\n'+inline+'\n'+read('product-options.js')+'\n'+read('products.js')+'\n'+read('product-details.js')+'\n'+read('checkout.js')+'\nwindow.cartSnapshot=()=>JSON.parse(JSON.stringify(cart));');
 const tick=()=>new Promise(r=>setTimeout(r,20));await tick();
 const card=w.document.querySelector('[data-catalog-id="1"]');assert.equal(card.querySelector('button:not(.heart)').textContent,'Kaufen');assert.ok(card.querySelector('.catalog-description').textContent.length<=105);assert.match(card.querySelector('.catalog-description').textContent,/…$/);
 const beforeChoices=[...$('horseModal').querySelectorAll('[data-color-id]')].map(b=>[b.dataset.regionId,b.dataset.colorId]);
 $('openHorseConfig').focus();$('openHorseConfig').click();await tick();
 const modal=$('horseModal');assert.equal(modal.getAttribute('role'),'dialog');assert.equal(modal.querySelector('.product-detail-description').textContent,description);assert.equal(modal.querySelector('.product-detail-description img'),null);assert.equal(modal.querySelector('.product-detail-price').textContent,'CHF 15.00');assert.equal(w.document.body.style.overflow,'hidden');
 assert.equal(modal.querySelector('.product-photo-thumbnails').children.length,2);const firstImage=$('horsePreview').src;
 modal.querySelector('.product-photo-thumbnails button:last-child').click();assert.equal(modal.querySelector('.product-photo-thumbnails button:last-child').getAttribute('aria-pressed'),'true');assert.match(modal.querySelector('.product-photo-caption').textContent,/Detail/);
 modal.querySelector('[data-region-id="primary"][data-color-id="rot"]').click();assert.equal(modal.querySelector('.product-photo-thumbnails button:last-child').getAttribute('aria-pressed'),'true');assert.equal($('horsePreview').src,firstImage);
 $('horseSize').value='60';$('horseSize').dispatchEvent(new w.Event('change'));assert.equal(modal.querySelector('.product-detail-price').textContent,'CHF 20.00');
 $('langFR').click();assert.equal(card.querySelector('button:not(.heart)').textContent,'Acheter');assert.equal(modal.querySelector('.product-detail-description').textContent,rows[0].description_fr);assert.match(modal.querySelector('.product-photo-caption').textContent,/Détail/);
 assert.deepEqual([...modal.querySelectorAll('[data-color-id]')].map(b=>[b.dataset.regionId,b.dataset.colorId]),beforeChoices);assert.equal($('horseSize').value,'60');
 modal.querySelector('.quantity-control button:last-of-type').click();$('horseAdd').click();await tick();
 const cart=w.cartSnapshot();assert.equal(cart.length,1);assert.equal(cart[0].quantity,2);assert.equal(cart[0].price,20);assert.equal(cart[0].sizeId,'60');assert.equal(cart[0].colorSelections.find(c=>c.region_id==='primary').color_id,'rot');assert.equal($('cartTotal').textContent,'CHF 45.00');
 $('cartDrawer').classList.remove('open');const single=w.document.querySelector('[data-catalog-id="80"] button:not(.heart)');single.focus();single.click();await tick();
 assert.equal($('simpleModal').querySelector('.product-detail-description').textContent,'Kurze Beschreibung.');assert.equal($('simpleModal').querySelector('.product-photo-thumbnails').hidden,true);assert.equal($('simpleImage').src,rows.at(-1).image_url);
 $('simpleModal').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await tick();assert.ok(!$('simpleModal').classList.contains('open'));assert.equal(w.document.activeElement,single);assert.equal(w.document.body.style.overflow,'');
 const zen=rows.find(p=>p.id===4);w.ProductDetails.mount(zen,'assets/zen-real.jpg');assert.equal($('zenModal').querySelector('.product-photo-thumbnails').children.length,3);$('zenModal').querySelector('.product-photo-thumbnails button:nth-child(2)').click();assert.match($('zenModal').querySelector('.product-photo-caption').textContent,/profil/);
 w.FavoProductPhotos={80:[{src:'https://images.example.test/side.jpg',de:'Seitenansicht',fr:'Vue de profil'},{src:'javascript:alert(1)'}]};
 w.openCatalogSimple(rows.at(-1),rows.at(-1).image_url);assert.equal($('simpleModal').querySelector('.product-photo-thumbnails').children.length,2);$('simpleModal').querySelector('.product-photo-thumbnails button:last-child').click();assert.equal($('simpleImage').src,'https://images.example.test/side.jpg');assert.match($('simpleModal').querySelector('.product-photo-caption').textContent,/profil/);
 assert.equal(JSON.stringify(rows),initial);assert.ok(requests.every(r=>r.method==='GET'));assert.ok(!requests.some(r=>r.url.includes('/functions/')));
 await tick();dom.window.close();console.log('PASS product details: short cards, Kaufen/Acheter, complete safe DE/FR text, galleries, preserved sizes/colors/quantity/cart totals, focus/Escape, no catalog mutation or payment requests.');
})().catch(e=>{console.error(e);process.exit(1)});
